version: '3.7'
services:
  nginx-maxinuss:
    image: nginx:latest
    container_name: nginx-maxinuss-container
    ports:
      - "8030:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - maxinussnetwork
  php-fpm-maxinuss:
    build: ./docker/php7.4
    container_name: php-maxinuss-container
    volumes:
      - ./:/var/www/html
    networks:
      - maxinussnetwork
  mysql-maxinuss:
    image: mysql:5.7
    container_name: mysql-maxinuss-container
    ports:
      - "3390:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: profile_api
      MYSQL_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
    networks:
      - maxinussnetwork
networks:
  maxinussnetwork:
    driver: "bridge"
volumes:
  data:
    driver: "local"